// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBODFoaNlf9uPJ3AN1EdoBW1I50A9vRF3M',
    appId: '1:438057570983:web:b81e23c3c36da802004182',
    messagingSenderId: '438057570983',
    projectId: 'bible-speak',
    authDomain: 'bible-speak.firebaseapp.com',
    storageBucket: 'bible-speak.firebasestorage.app',
    measurementId: 'G-P7261J5TGK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi8nN0zS75vu1oIbuoG0K8W6-ddJC-D94',
    appId: '1:438057570983:android:100297bceb3eef0b004182',
    messagingSenderId: '438057570983',
    projectId: 'bible-speak',
    storageBucket: 'bible-speak.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5DBDdj3bvxmN7lnjvnTewpFJM5ah_O0g',
    appId: '1:438057570983:ios:a5a02a97c2c3112d004182',
    messagingSenderId: '438057570983',
    projectId: 'bible-speak',
    storageBucket: 'bible-speak.firebasestorage.app',
    iosBundleId: 'com.example.bibleSpeak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5DBDdj3bvxmN7lnjvnTewpFJM5ah_O0g',
    appId: '1:438057570983:ios:a5a02a97c2c3112d004182',
    messagingSenderId: '438057570983',
    projectId: 'bible-speak',
    storageBucket: 'bible-speak.firebasestorage.app',
    iosBundleId: 'com.example.bibleSpeak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBODFoaNlf9uPJ3AN1EdoBW1I50A9vRF3M',
    appId: '1:438057570983:web:3e78533f6d803d78004182',
    messagingSenderId: '438057570983',
    projectId: 'bible-speak',
    authDomain: 'bible-speak.firebaseapp.com',
    storageBucket: 'bible-speak.firebasestorage.app',
    measurementId: 'G-SH77VTBDEZ',
  );
}
